title: "Dmitrij Levyj"
description: "Data Science Portfolio"
theme: "minimal-mistakes" # or any other theme you prefer
baseurl: "" # Leave this empty unless you are using a subdirectory
url: "https://dmitrij-levyj.github.io"
